#!/usr/bin/env python3
"""Replay real isolated Whisper/Codex artifacts through the app's actual Swift validators.

Fixtures are synthetic German TTS, generated by the isolated 2026-09-06 pipeline.
No network, inference, production database, UIKit, or mock reimplementation of validators.
"""
from pathlib import Path
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
server = (ROOT / "Classes/ServerTranscriptionManager.swift").read_text()
engine = (ROOT / "Classes/TranscriptionEngine.swift").read_text()

def declaration(source, signature):
    start = source.index(signature)
    brace = source.index("{", start)
    depth = 0
    for end in range(brace, len(source)):
        depth += (source[end] == "{") - (source[end] == "}")
        if not depth:
            return source[start:end + 1]
    raise AssertionError(signature)

types = "\n".join(declaration(server, signature) for signature in [
    "private struct ICServerSummaryArtifact:", "private struct ICServerChaptersArtifact:",
    "private struct ICServerAdsArtifact:", "private struct ICServerMedia:",
])
types += "\n" + declaration(engine, "@objc class ICTranscriptCue:")
methods = "\n".join(declaration(server, signature) for signature in [
    "private func validateServerArtifacts(", "private func sameMillisecond(", "private func serverContractError(",
    "private func validateServerTranscriptBounds(",
]).replace("private func validateServerArtifacts(", "func validateServerArtifacts(").replace("private func validateServerTranscriptBounds(", "func validateServerTranscriptBounds(")
methods += "\n" + "\n".join(declaration(engine, signature) for signature in [
    "struct ICSRTRejection", "private func parsePersistedSRTDetailed(",
    "private func parsePersistedSRTTime(", "private func isCanonicalServerSRTTimeLine(",
    "func validateServerSRTData(",
])
fixture = r'''
import Foundation
import CryptoKit
TYPES
final class ICDiagnosticLogger: @unchecked Sendable {
 static let shared = ICDiagnosticLogger()
 func logEvent(_ event: String, message: String, metadata: [String: String]) {}
}
private final class Validator {
METHODS
}
@main struct Test {
 static func main() throws {
  let root = URL(fileURLWithPath: CommandLine.arguments[1])
  let reportURL = URL(fileURLWithPath: CommandLine.arguments[2])
  let report = try JSONSerialization.jsonObject(with: Data(contentsOf: reportURL)) as! [String: Any]
  let data = try Data(contentsOf: root.appendingPathComponent("transcript.srt"))
  let chapterData = try Data(contentsOf: root.appendingPathComponent("chapters.json"))
  let adsData = try Data(contentsOf: root.appendingPathComponent("ads.json"))
  let summaryData = try Data(contentsOf: root.appendingPathComponent("summary.json"))
  let revision = "sha256:" + SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
  let decoder = JSONDecoder(), validator = Validator()
  let cues = try validator.validateServerSRTData(data, for: "controlled-library")
  let chapters = try decoder.decode(ICServerChaptersArtifact.self, from: chapterData)
  let ads = try decoder.decode(ICServerAdsArtifact.self, from: adsData)
  let summary = try decoder.decode(ICServerSummaryArtifact.self, from: summaryData)
  let duration = report["duration_seconds"] as! Double
  try validator.validateServerTranscriptBounds(cues, serverDuration: duration)
  try validator.validateServerArtifacts(chapters, ads: ads, summary: summary, transcriptRevision: revision, serverDuration: duration)
  precondition(ads.segments.count == 1 && ads.segments[0].title == "Sponsor: Beispiel Kaffee")
  let mediaData = try JSONSerialization.data(withJSONObject: ["audio_sha256": report["source_audio_sha256"]!])
  let media = try decoder.decode(ICServerMedia.self, from: mediaData)
  precondition(media.audioSHA256 == "92747209c31b54463fa69e40d7b29b15894a13ff00664e86ca8066112984b6d0")
  var rejected = 0
  func rejects(_ block: () throws -> Void) {
   do { try block(); fatalError("Mutated artifact was accepted") } catch { rejected += 1 }
  }
  rejects { try validator.validateServerTranscriptBounds([ICTranscriptCue(start: 0, end: duration + 1, text: "Beyond the audio.")], serverDuration: duration) }
  rejects { try validator.validateServerTranscriptBounds(cues, serverDuration: nil) }
  rejects { try validator.validateServerTranscriptBounds(cues, serverDuration: .infinity) }
  try validator.validateServerTranscriptBounds([ICTranscriptCue(start: 0, end: 1.235, text: "Rounded boundary.")], serverDuration: 1.2348)
  rejects { try validator.validateServerTranscriptBounds([ICTranscriptCue(start: 0, end: 1.236, text: "Beyond rounded boundary.")], serverDuration: 1.2348) }
  let millisecondOverlap = "1\n00:00:00,000 --> 00:00:01,000\nFirst sentence.\n\n2\n00:00:00,999 --> 00:00:02,000\nSecond sentence.\n"
  do { _ = try validator.validateServerSRTData(Data(millisecondOverlap.utf8), for: "controlled-library"); fatalError("One-millisecond server SRT overlap was accepted") } catch { rejected += 1 }
  rejects { try validator.validateServerArtifacts(chapters, ads: ads, summary: summary, transcriptRevision: "sha256:wrong", serverDuration: duration) }
  rejects { try validator.validateServerArtifacts(chapters, ads: ads, summary: summary, transcriptRevision: revision, serverDuration: duration + 1) }
  var overlapping = try JSONSerialization.jsonObject(with: adsData) as! [String: Any]
  let segments = overlapping["segments"] as! [[String: Any]]
  overlapping["segments"] = segments + segments
  let badAds = try decoder.decode(ICServerAdsArtifact.self, from: JSONSerialization.data(withJSONObject: overlapping))
  rejects { try validator.validateServerArtifacts(chapters, ads: badAds, summary: summary, transcriptRevision: revision, serverDuration: duration) }
  let original = String(data: data, encoding: .utf8)!
  let badTimeLine = original.replacingOccurrences(of: " --> ", with: " -> ")
  rejects { _ = try validator.validateServerSRTData(Data(badTimeLine.utf8), for: "controlled-library") }
  var lines = original.components(separatedBy: "\n")
  let times = lines.indices.filter { lines[$0].contains(" --> ") }
  let second = times[1]
  lines[second] = "00:00:00,000 --> " + lines[second].components(separatedBy: " --> ")[1]
  rejects { _ = try validator.validateServerSRTData(Data(lines.joined(separator: "\n").utf8), for: "controlled-library") }
  print("Real app validators accepted \(cues.count) cues, \(chapters.chapters.count) chapters, one sponsor; rejected \(rejected) corruptions; source SHA decoded.")
 }
}
'''.replace("TYPES", types).replace("METHODS", methods)
with tempfile.TemporaryDirectory(prefix="instacast-real-client-") as directory:
    path = Path(directory)
    (path / "main.swift").write_text(fixture)
    subprocess.run(["xcrun", "swiftc", "-swift-version", "6", "-parse-as-library", str(path / "main.swift"), "-o", str(path / "test")], check=True)
    subprocess.run([str(path / "test"), str(ROOT / "Tools/fixtures/server-sponsor-e2e"), str(ROOT / "Tools/transcription-server/2026-09-06-sponsor-e2e.json")], check=True)
